Добавил type hints
groupbwt/scrapy-command-new pull request #10
Opened 2020-03-23 16:30 UTC by DmitryKovtun

- Добавил type hints во все шаблоны
(Исправил #2 )

2020-03-24 09:36 UTC, KristobalJunta requested changes

2020-03-24 09:36 UTC, KristobalJunta commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
@DmitryKovtun тут скорее всего, стоит поменять Iterator на Generator, также добавить в типы Request
https://docs.python.org/3/library/typing.html#typing.Generator

2020-03-24 09:36 UTC, KristobalJunta commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
Также в middleware этот же момент, но тут я не уверен, по докам Scrapy тип Iterator тоже вроде как подходит

2020-03-24 09:38 UTC, DmitryKovtun commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
@KristobalJunta Сейчас исправлю на Generator и посмотрю что упустил.

2020-03-24 16:22 UTC, DmitryKovtun commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
@KristobalJunta Обсудили эти типы. Менять или как?

2020-03-24 18:56 UTC, KristobalJunta commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
@DmitryKovtun а что по результату? Если текущая аннотация тайпчекается и она короче, чем вариант с generator, то оставляем как есть сейчас.

2020-03-25 16:57 UTC, DmitryKovtun commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
@KristobalJunta mypy ошибок не выкидывает на это. Проверил.

2020-03-28 16:02 UTC, KristobalJunta commented on scrapy_new/templates/spider.py.mako
> +    def parse(self, response: Response) -> Iterator[Item]:
Отлично, спасибо

2020-03-28 16:02 UTC, merged